---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  channel: stable-2.2
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: test-aap-operator-automation
  sourceNamespace: openshift-marketplace
